/* Generated by cbindgen from libbeachcomber-ffi. Do not edit by hand — run `cargo xtask gen-header`. */

#ifndef BEACHCOMBER_H
#define BEACHCOMBER_H

/* Warning, this file is autogenerated by cbindgen. Don't manually edit this file. */

#include <stdbool.h>
#include <stdint.h>

/**
 * `bc_get` flag: evict the cache entry and re-execute the provider before
 * returning.
 */
#define BC_GET_FORCE (1 << 0)

/**
 * `bc_get` flag: if the entry is stale, wait for inline re-execution.
 */
#define BC_GET_WAIT (1 << 1)

/**
 * Opaque client handle returned by [`bc_client_new`].
 *
 * Construction never fails from the caller's point of view: a malformed
 * `options_json` is recorded here and surfaced on the handle's first
 * operation instead of failing the constructor.
 */
typedef struct BcClient BcClient;

/**
 * Opaque handle to a persistent connection for multiple queries.
 *
 * The connection is guarded by an internal mutex: a caller that finds it
 * already locked gets a `kind: "busy"` envelope immediately rather than
 * blocking or interleaving its request with another caller's on the same
 * socket. `state` also carries a deferred construction error, the same
 * pattern [`BcClient`] uses — [`bc_session_open`] never returns NULL for a
 * reason short of allocation failure.
 */
typedef struct BcSession BcSession;

/**
 * Opaque handle to a watch stream.
 *
 * Guarded the same way [`BcSession`] is: an internal mutex that
 * [`bc_watch_next`] takes with `try_lock`, yielding `kind: "busy"` for a
 * concurrent caller rather than blocking. `cancelled` is deliberately
 * **outside** that mutex — [`bc_watch_cancel`] is the one call in this
 * crate documented as safe to invoke from another thread while an op is in
 * flight, and it must not itself block on the lock a pending
 * [`bc_watch_next`] is holding.
 */
typedef struct BcWatch BcWatch;

/**
 * Returns the library's build version as a static, NUL-terminated string
 * that must **not** be passed to [`envelope::bc_string_free`].
 */
const char *bc_version(void);

/**
 * Creates a new client handle. `options_json` is nullable; recognised keys
 * are `socket_path`, `timeout_ms` and `autostart`. Never returns NULL — a
 * malformed `options_json` still yields a handle, with the parse error
 * deferred to the handle's first operation rather than failing here.
 *
 * # Safety
 * `options_json` must be NULL or a valid pointer to a NUL-terminated string.
 */
BcClient *bc_client_new(const char *options_json);

/**
 * Frees a client handle. Null-safe.
 *
 * # Safety
 * `client` must be either NULL or a pointer previously returned by
 * [`bc_client_new`], not yet freed.
 */
void bc_client_free(BcClient *client);

/**
 * Query a single key. `path` is nullable (global providers). `flags` is a
 * bitmask of [`BC_GET_FORCE`] / [`BC_GET_WAIT`]; any other bit set yields a
 * `bad_flags` envelope.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `key` must be
 * non-null and NUL-terminated; `path` must be NULL or NUL-terminated.
 */
char *bc_get(BcClient *client, const char *key, const char *path, uint32_t flags);

/**
 * Store data into a virtual provider. `json_data` must parse as JSON.
 * `ttl` and `path` are nullable.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `key` and
 * `json_data` must be non-null and NUL-terminated; `ttl` and `path` must be
 * NULL or NUL-terminated.
 */
char *bc_put(BcClient *client,
             const char *key,
             const char *json_data,
             const char *ttl,
             const char *path);

/**
 * Clear the cached entry for a virtual provider key without dropping the
 * registry entry. `path` is nullable.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `key` must be
 * non-null and NUL-terminated; `path` must be NULL or NUL-terminated.
 */
char *bc_put_null(BcClient *client, const char *key, const char *path);

/**
 * Trigger recomputation of a provider. `path` is nullable.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `key` must be
 * non-null and NUL-terminated; `path` must be NULL or NUL-terminated.
 */
char *bc_refresh(BcClient *client, const char *key, const char *path);

/**
 * List all cache entries currently held by the daemon.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`].
 */
char *bc_status(BcClient *client);

/**
 * Run an introspect query. `options_json` is nullable; its only recognised
 * key is `duration_secs`, consulted by the `procs` subject only.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `subject` must
 * be non-null and NUL-terminated; `options_json` must be NULL or
 * NUL-terminated.
 */
char *bc_introspect(BcClient *client, const char *subject, const char *options_json);

/**
 * Ask the daemon for its protocol and build versions.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`].
 */
char *bc_hello(BcClient *client);

/**
 * Resolve a virtual field (`key` = `"provider.field"`) or a path
 * expression (`key` = a bare provider name) — client-side, exactly as
 * `comb get`'s resolution layer does.
 *
 * `cwd` is required: NULL returns an error envelope rather than falling
 * back to the process's own working directory — this library must never
 * read ambient state on the caller's behalf. `env_json` and
 * `overrides_json` are nullable, meaning "none supplied".
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `key` and `cwd`
 * must be non-null and NUL-terminated; `env_json` and `overrides_json` must
 * be NULL or NUL-terminated.
 */
char *bc_resolve(BcClient *client,
                 const char *key,
                 const char *cwd,
                 const char *env_json,
                 const char *overrides_json);

/**
 * Evaluate a value expression in any of the three forms canon
 * `field_resolution.md` (invariant 14) defines: a bare expression, exactly
 * one `{{ expr }}` tag (keeps the expression's natural type), or literal
 * text and/or several tags (string-valued) — the same evaluator
 * `bc_resolve` uses for a declared virtual field, but for a raw expression
 * that need not be registered anywhere. Every reference the source makes
 * is threaded in: `env.*` from `env_json`, and `cache.*` / plain
 * `provider.field` refs fetched from the daemon, following virtual fields
 * transitively — the same closure `bc_resolve` uses. A missing or unknown
 * ref (an absent `env.*`, a daemon miss, or a daemon-rejected key such as
 * an unregistered provider) is falsy at any depth, not an error.
 *
 * `cwd` is required, matching `bc_resolve`'s signature (see there for
 * why) — a bare `cwd` reference in a field expression is reserved for a
 * later task and not evaluated by `bc_eval` today.
 *
 * # Safety
 * `client` must be a valid pointer from [`bc_client_new`]; `template_str`
 * and `cwd` must be non-null and NUL-terminated; `env_json` and
 * `overrides_json` must be NULL or NUL-terminated.
 */
char *bc_eval(BcClient *client,
              const char *template_str,
              const char *cwd,
              const char *env_json,
              const char *overrides_json);

/**
 * Opens a persistent session on `client`'s connection. Never returns NULL:
 * a `client` whose own construction failed, or a daemon that is
 * unreachable when the underlying connection is attempted, is recorded on
 * the handle and surfaced on the session's first operation instead.
 *
 * # Safety
 * `client` must be a valid, non-null pointer previously returned by
 * [`bc_client_new`], not yet freed.
 */
BcSession *bc_session_open(BcClient *client);

/**
 * Closes and frees a session handle. Null-safe.
 *
 * # Safety
 * `session` must be either NULL or a pointer previously returned by
 * [`bc_session_open`], not yet closed.
 */
void bc_session_close(BcSession *session);

/**
 * Query a single key on this session's persistent connection. `flags` is
 * the same [`BC_GET_FORCE`] / [`BC_GET_WAIT`] bitmask [`bc_get`] takes.
 *
 * # Safety
 * `session` must be a valid pointer from [`bc_session_open`]; `key` must
 * be non-null and NUL-terminated; `path` must be NULL or NUL-terminated.
 */
char *bc_session_get(BcSession *session, const char *key, const char *path, uint32_t flags);

/**
 * Store data into a virtual provider on this session's persistent
 * connection. `json_data` must parse as JSON; `ttl` and `path` are
 * nullable.
 *
 * # Safety
 * `session` must be a valid pointer from [`bc_session_open`]; `key` and
 * `json_data` must be non-null and NUL-terminated; `ttl` and `path` must be
 * NULL or NUL-terminated.
 */
char *bc_session_put(BcSession *session,
                     const char *key,
                     const char *json_data,
                     const char *ttl,
                     const char *path);

/**
 * Sets connection context on this session so subsequent queries don't need
 * an explicit `path`.
 *
 * # Safety
 * `session` must be a valid pointer from [`bc_session_open`]; `path` must
 * be non-null and NUL-terminated.
 */
char *bc_session_set_context(BcSession *session, const char *path);

/**
 * Opens a watch on `key`. Returns NULL only on allocation failure — any
 * other failure (a `client` whose own construction failed, or the watch
 * request itself failing) is recorded on the handle and surfaced on the
 * first [`bc_watch_next`] call instead.
 *
 * # Safety
 * `client` must be a valid, non-null pointer from [`bc_client_new`]; `key`
 * must be non-null and NUL-terminated; `path` must be NULL or
 * NUL-terminated.
 */
BcWatch *bc_watch_open(BcClient *client, const char *key, const char *path);

/**
 * Waits for the next event on `w`. `timeout_ms`: `-1` blocks indefinitely,
 * `0` polls (returns immediately if nothing is ready), `>0` waits that
 * long. Distinguishes five outcomes, all machine-readable without string
 * matching (see [`WatchOutcome`]): `event`, `timeout`, `eof`, `cancelled`
 * (via `ok:true` plus an `outcome` field), and `error` (the ordinary
 * `ok:false` envelope, already machine-readable via `error.kind`).
 * `error` is reserved for the daemon actively rejecting the watched key
 * (a malformed response line, or the `ServerError`/`ParseError` a bad
 * nested field path produces) — any lower-level socket failure (a reset
 * connection, or even a failing `set_read_timeout`, observed on macOS as
 * `EINVAL` from `setsockopt` on an already-reset unix socket rather than
 * the loss surfacing on the next read) is treated as `eof`: from a
 * caller's point of view the stream is over either way, and a binding
 * should not have to special-case platform-specific socket-teardown
 * quirks as a distinct failure mode.
 *
 * Internally this holds the socket's read timeout to at most
 * [`WATCH_POLL_TICK`] per attempt and loops, re-checking the cancellation
 * flag and (for `timeout_ms > 0`) the deadline between attempts, rather
 * than issuing one read for the full requested wait — that is what lets
 * [`bc_watch_cancel`], called from another thread mid-wait, unblock a
 * pending call within about one tick instead of only at the next natural
 * wakeup. A timed-out attempt's partially-read bytes (if a line arrived
 * split across attempts) are preserved across retries by
 * [`libbeachcomber::WatchStream::read_line_buffered`] rather than
 * discarded, so this cannot silently drop half of an event.
 *
 * # Safety
 * `w` must be a valid, non-null pointer previously returned by
 * [`bc_watch_open`], not yet freed.
 */
char *bc_watch_next(BcWatch *w, int32_t timeout_ms);

/**
 * Cancels a pending or future [`bc_watch_next`] call on `w`. Null-safe.
 * The sole function in this crate documented as safe to call from a
 * different thread than the one driving `w`'s other operations — it never
 * takes `w`'s internal lock, only sets an atomic flag a pending
 * `bc_watch_next` polls for. A `bc_watch_next` call already in flight
 * observes it within about [`WATCH_POLL_TICK`]; every call after this one
 * observes it immediately.
 *
 * # Safety
 * `w` must be either NULL or a pointer previously returned by
 * [`bc_watch_open`], not yet freed.
 */
void bc_watch_cancel(BcWatch *w);

/**
 * Frees a watch handle. Null-safe.
 *
 * # Safety
 * `w` must be either NULL or a pointer previously returned by
 * [`bc_watch_open`], not yet freed.
 */
void bc_watch_free(BcWatch *w);

/**
 * Frees a string returned by any `bc_*` function that documents its result
 * as caller-owned. Null-safe. Never call this on `bc_version()`'s return
 * value — that string is static and not owned by the caller.
 *
 * # Safety
 * `ptr` must be either NULL or a pointer previously returned by one of this
 * crate's `char *`-returning functions, not yet freed.
 */
void bc_string_free(char *ptr);

#endif  /* BEACHCOMBER_H */
