import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guide',
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [{type: 'autogenerated', dirName: 'ecosystem'}],
    },
    {
      type: 'category',
      label: 'Internals',
      items: [{type: 'autogenerated', dirName: 'internals'}],
    },
    {
      type: 'category',
      label: 'About',
      items: [{type: 'autogenerated', dirName: 'about'}],
    },
  ],
};

export default sidebars;
